### ISSUE TITLE
PurgatoryX broken

### ISSUE THREAD

**Issue by insickin** [DirtyRacer1337/PhoenixAdult.bundle#11]
I saw that PurgatoryX is being supported (thanks @bigbadwolfie )  but when I try to tag my PurgatoryX scene's the agent comes back with: No matches found, am I doing something wrong or is there something wrong with the agent?

1. Scene URL = https://tour.purgatoryx.com/view/69/the-last-straw-vol-1-e3?trilogy=31
2. File Name = PurgatoryX - The Last Straw Vol 1 E3.mp4
3. Log File = [com.plexapp.agents.phoenixadult.log](https://github.com/DirtyRacer1337/PhoenixAdult.bundle/files/5685392/com.plexapp.agents.phoenixadult.log)

**Comment by bigbadwolfie** [comment]
Think I got it. I'll add something to remove The Last Straw Vol **1 E3**

The search only works when The Last Straw Vol is fed the search.

**Comment by DirtyRacer1337** [comment]
Adding date and changing name to `Last Straw` should help

**Comment by insickin** [comment]
Picked your latest update @bigbadwolfie but it still can't find anything, still: No matches

[com.plexapp.agents.phoenixadult.log](https://github.com/DirtyRacer1337/PhoenixAdult.bundle/files/5685448/com.plexapp.agents.phoenixadult.log)

I tried searching with:
Purgatoryx - the Last Straw Vol 1 E3
Purgatoryx - Last Straw
even with the scene's date

**Comment by DirtyRacer1337** [comment]
Now search on site stopped working for me

**Comment by bigbadwolfie** [comment]
Can revert the Change. The search is not only keyword sensitive, its case sensitive. The search generated on the page using the live data is much better, but I don't know how to grab those results.

![image](https://user-images.githubusercontent.com/73149071/102024839-5b225c80-3d62-11eb-8366-f8432139d942.png)

For Example:
Genie Wishes - does not return results
Genie Wishes Vol - does not return results
Genie - returns results

**Comment by DirtyRacer1337** [comment]
@bigbadwolfie screw that search, just go through `Google Search`

**Comment by bigbadwolfie** [comment]
I made the change to google. I think I prevented all the duplicate link cases, but let me know.

@DirtyRacer1337 @insickin
