### ISSUE TITLE
The plugins not show me in Synology Plex

### ISSUE THREAD

**Issue by drraymond27** [DirtyRacer1337/PhoenixAdult.bundle#19]
**Describe the bug**
I bought a Synology NAS, then I installed Plex, moved the plugins like the instructions said, but the PhoenixAdult metadata not show me in Plex, help

**Include**
1. Scene URL
2. File Name
3. Log File

**Comment by insickin** [comment]
Have you restarted your Plex server?

**Comment by drraymond27** [comment]
Yes, I do everything, well I move the Plugins folder, from Windows to NAS, but not is listed under agents.
something I did wrong but I don't know what

**Comment by drraymond27** [comment]
Solved, thanks!
