### ISSUE TITLE
Hustler No Match

### ISSUE THREAD

**Issue by drraymond27** [DirtyRacer1337/PhoenixAdult.bundle#25]
Describe the bug
Hustler No Matching by DateID, URL or anything

Include

https://www.hustler.com/model/capri-cavalli/movie/20130901/CAPRI_CAVALLI_IN_A_GIRLFRIEND_S_REVENGE__2
Hustler - Capri Cavalli in A Girlfriend's Revenge #2.mp4
[com.plexapp.agents.phoenixadult.log](https://github.com/DirtyRacer1337/PhoenixAdult.bundle/files/5720283/com.plexapp.agents.phoenixadult.log)

**Comment by durmonator** [comment]
It would appear Hustler's search URL has changed:

https://www.hustler.com/search/A+Girlfriends+Revenge+2

**Comment by durmonator** [comment]
Further on to my comment, it appears their entire search design and possible content page has been redesigned, so it will need a site rework in the code for these to pick up

**Comment by DirtyRacer1337** [comment]
Fixed in 6633f7b1fbb819295588d9b01a13ce0f6c35de02
