### ISSUE TITLE
Data 18 Image Issue

### ISSUE THREAD

**Issue by durmonator** [DirtyRacer1337/PhoenixAdult.bundle#26]
Hey, I am trying to match a few old Hot and Mean scenes from Data18, but I can't seem to find a working naming convention, I have tried Data18, Data18Content, Data18Content - Brazzers, Data18Content - HotandMean and nothing seems to match anything, what would be the optimum convention for this matcher?

Thanks

**Comment by durmonator** [comment]
Added the code files in again and it appears to have picked it up this time, odd, one thing though, it doesn't appear to be grabbing the scene poster from the trailer you get on the content page, but instead it pulls in the images underneath in the photo set

**Comment by bigbadwolfie** [comment]
Should use Data18 Content or Data18Content. I made some changes in last PR to fix the results. If the search doesn't work you can grab the sceneID from the end of the URL.

As for the image embedded in the page. I skipped that in preference of the image set, but made it grab it if there is no imageset. I can make it so it pulls it by default.
