### ISSUE TITLE
New Site Support

### ISSUE THREAD

**Issue by insickin** [DirtyRacer1337/PhoenixAdult.bundle#3]
Add the sites you would like to see supported here

**Comment by insickin** [comment]
Can https://tour.purgatoryx.com be added?

**Comment by PHXMIC** [comment]
Plumperpass.com

**Comment by insickin** [comment]
Can https://ftvmilfs.com/ and https://www.ftvgirls.com/ be added?

**Comment by insickin** [comment]
Can http://www.ztod.com/ be added?

**Comment by drraymond27** [comment]
Can you add www.Fakings.com and  www.axxxteca.com ?

**Comment by insickin** [comment]
Can https://www.aziani.com be added?

**Comment by insickin** [comment]
Can https://tour.mariskax.com be added?

**Comment by insickin** [comment]
Can https://tours.lasublimexxx.com/tour/ be added?

**Comment by insickin** [comment]
Can https://dillionation.com be added?

**Comment by bigbadwolfie** [comment]
> Can https://dillionation.com be added?

#37 Done

**Comment by drraymond27** [comment]
https://www.sunnylanelive.com/

Please and Thanks

**Comment by bigbadwolfie** [comment]
> Can
> http://www.ztod.com/
> https://www.hotguysfuck.com/
> https://sexmex.xxx/tour/
> https://www.explicite-art.com/visitor/
> https://blackpayback.com/tour/
> https://www.casualteensex.com/
> be added?

~~https://sexmex.xxx/tour/~~
~~https://www.explicite-art.com/visitor/~~
~~https://blackpayback.com/tour/~~
#39 
#41 

http://www.ztod.com/ - Already Exists
https://www.hotguysfuck.com/ - I tried writing this one, but it has some sort of scraping protection that I didn't know how to bypass
https://www.casualteensex.com/ - No way to search this site since the videos don't have their own pages

**Comment by drraymond27** [comment]
Can add
https://www.sunnylanelive.com/
http://www.rahyndeejames.com/
www.fakings.com
www.leche69.com
www.axxxteca.com
www.blackpatrol.com
www.xxxpawn.com
www.mypervyfamily.com

Please and Thanks

**Comment by insickin** [comment]
Can https://pissplay.com/ be added much of there scenes are on https://bruceandmorgan.net which is already supported by the agent but they are apparently moving site

**Comment by insickin** [comment]
Can https://www.frolicme.com/erotic-films/ be added?

**Comment by insickin** [comment]
Can https://hornyhostel.com/ be added?
