### ISSUE TITLE
R18 (NO Results Found)

### ISSUE THREAD

**Issue by FevLoad** [DirtyRacer1337/PhoenixAdult.bundle#36]
**Describe the bug**
I can match anything using R18 while I can when I use (Javbus ID-Here)

**Include**
1. Scene URL : https://www.r18.com/videos/vod/movies/detail/-/id=juy00462/?i3_ref=search&i3_ord=1
2. File Name: Juy-462
3. Log File: [com.plexapp.agents.phoenixadult](https://pastebin.com/UG4AtX3N)

**Comment by DirtyRacer1337** [comment]
Filename should start with `JAV` like `JAV - JUY-462`

**Comment by FevLoad** [comment]
Is this code (JAV) FOR R18!!?

**Comment by DirtyRacer1337** [comment]
For me images exist, site have cloudflare protection(no solution for that), thats the problem.

**Comment by FevLoad** [comment]
How can I make them appear or get scrap for me?!

**Comment by FevLoad** [comment]
Thanks for the help
`JAV` Did the trick
