### ISSUE TITLE
SexMex without Actors and photos

### ISSUE THREAD

**Issue by drraymond27** [DirtyRacer1337/PhoenixAdult.bundle#40]
**Describe the bug**
The new SexMex sites support don't show actors and photos in Poster

**Include**
1. https://sexmex.xxx/tour/models/janeth-rubio.html
2. SexMex - Janeth Paying with sex
3. [com.plexapp.agents.phoenixadult.log](https://github.com/DirtyRacer1337/PhoenixAdult.bundle/files/5761121/com.plexapp.agents.phoenixadult.log)

**Comment by bigbadwolfie** [comment]
#41 Think it has to do with the update typo
