### ISSUE TITLE
Puta Locura no Match

### ISSUE THREAD

**Issue by drraymond27** [DirtyRacer1337/PhoenixAdult.bundle#45]
**Describe the bug**
Puta Locura no Match anything

**Include**
1. https://www.putalocura.com/pilladas-torbe/agatha
2. Puta Locura - Agatha
3. [com.plexapp.agents.phoenixadult.log](https://github.com/DirtyRacer1337/PhoenixAdult.bundle/files/5775735/com.plexapp.agents.phoenixadult.log)

**Comment by bigbadwolfie** [comment]
Going to also add a Spanish/English tag in the results for this one

![image](https://user-images.githubusercontent.com/73149071/103785676-7e5ec580-5009-11eb-836c-deadcc9a9059.png)
