### ISSUE TITLE
Wicked no mactch

### ISSUE THREAD

**Issue by drraymond27** [DirtyRacer1337/PhoenixAdult.bundle#51]
**Describe the bug**
Wicked no match at all

**Include**
1. https://www.wicked.com/en/movie/CAPTAIN-MARVEL-XXX-AN-AXEL-BRAUN-PARODY/77682
2. Wicked - Captain Marvel XXX An Axel Braun Parody
3. [com.plexapp.agents.phoenixadult.log](https://github.com/DirtyRacer1337/PhoenixAdult.bundle/files/5789888/com.plexapp.agents.phoenixadult.log)

**Comment by bigbadwolfie** [comment]
The search is Wicked Pictures, but I don't agree with it being as such.

In fact the abbreviation wkd tied to Wicked
