### ISSUE TITLE
Elegant Angel no shows actors

### ISSUE THREAD

**Issue by drraymond27** [DirtyRacer1337/PhoenixAdult.bundle#53]
**Describe the bug**
Elegant Angel No show Actors and no search for some DVD's
For Example in the search that I made, "The Most Beautiful Girls In Porn 4", the search show the 1, 2, 3, but not 4; and the other "Busty Women In Heat" only show the part 2

**Include**
1. https://www.elegantangel.com/shop/3061047/most-beautiful-girls-in-porn-4-the-porn-movies.html
   https://www.elegantangel.com/shop/2685050/busty-women-in-heat-porn-movies.html
2. New Sensations - The Most Beautiful Girls In Porn 4
   DDBusty - Busty Women In Heat
3. [com.plexapp.agents.phoenixadult.log](https://github.com/DirtyRacer1337/PhoenixAdult.bundle/files/5792821/com.plexapp.agents.phoenixadult.log)

**Comment by bigbadwolfie** [comment]
Doesn't fix the no actors.

**Comment by bigbadwolfie** [comment]
> Doesn't fix the no actors. I'll look at that too.

Done
