### ISSUE TITLE
(Older) Blacked Raw scene's missing cast info

### ISSUE THREAD

**Issue by insickin** [DirtyRacer1337/PhoenixAdult.bundle#57]
Hi when tagging a couple of Blacked Raw scene's I don't get cast photo's/info, it seems that it is a problem with older scenes, the latest scene tags fine!

Maybe the problem is also affecting the other Strike3 Network sites, I haven't tested that.

For example:
1. Scene URL = https://www.blackedraw.com/the-biggest-ive-ever-seen
2. File Name = Blacked Raw - The Biggest I've Ever Seen
3. Log File = [com.plexapp.agents.phoenixadult.log](https://github.com/DirtyRacer1337/PhoenixAdult.bundle/files/5795771/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Fixed in 359227f5fbaf146091df4451f3f9526b40635a42
