### ISSUE TITLE
Cumlouder without Actors

### ISSUE THREAD

**Issue by drraymond27** [DirtyRacer1337/PhoenixAdult.bundle#67]
**Describe the bug**
Cumlouder erase Actors when refresh

**Include**
1. https://www.cumlouder.com/porn-video/hot-lesbian-sex-with-nekane-and-julia/
2. Cumlouder - Nekane vs Julia de Lucia
3. [com.plexapp.agents.phoenixadult.log](https://github.com/DirtyRacer1337/PhoenixAdult.bundle/files/5862735/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Fixed in 01ddb5a28103799ba6cf36676865c17388452196
