### ISSUE TITLE
lubed no cast photo/info

### ISSUE THREAD

**Issue by insickin** [DirtyRacer1337/PhoenixAdult.bundle#83]
When tagging lubed I get no cast photo/info. The agent gives 2 of the same results when searching. Both with a score of 100%

After tagging more scene's it seems that the whole Porn Pros network is affected.

**Include**
1. Scene URL = https://lubed.com/video/shower-freak
2. File Name = Lubed - Shower Freak.mp4
3. Log File = [com.plexapp.agents.phoenixadult.log](https://github.com/DirtyRacer1337/PhoenixAdult.bundle/files/5894990/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Fixed in a090cdedf3228c26496b7c7a18332347724d192e and 9b39ed1db35b0a81c0df5d66104d94eb31f5f7f0

**Comment by insickin** [comment]
Thanks that fixed it!
