### ISSUE TITLE
PassionHD can't find a scene

### ISSUE THREAD

**Issue by insickin** [DirtyRacer1337/PhoenixAdult.bundle#84]
I am trying to tag "Passion-HD - Bathing Beauty" with Dani Daniels but when searching for the scene it only finds a Bathing Beauty scene with Alison Star.

1. Scene URL = https://passion-hd.com/video/bathing-beauty--3
2. File Name = PassionHD - Bathing Beauty.mp4
3. Log File = [com.plexapp.agents.phoenixadult.log](https://github.com/DirtyRacer1337/PhoenixAdult.bundle/files/5898542/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
File Name `PassionHD - Bathing Beauty 3` should work, I test it later

**Comment by insickin** [comment]
Thanks that worked!

**Comment by insickin** [comment]
Hi I have another scene that I can't find: https://passion-hd.com/video/best-of-both-worlds-part-2 can you help me again?

**Comment by DirtyRacer1337** [comment]
`best of both worlds part 2` it's can work through `direct url`
works with 67a81bfd4828093fdf0e2b4295d872e9c6ce10f2

**Comment by insickin** [comment]
It does't work, when looking in the log I see that the agent tries to get https://www.passion-hd.com/video/best-of-both-worlds-part--2 "--" instead off https://passion-hd.com/video/best-of-both-worlds-part-2 "-"

**Comment by DirtyRacer1337** [comment]
Fixed in 2e8d28c01dac3d1bb52f3a8c131f5426a8dff63a

**Comment by insickin** [comment]
Yes, now it works!
