### ISSUE TITLE
Can't find a Spizoo/FirstClassPOV scene

### ISSUE THREAD

**Issue by insickin** [DirtyRacer1337/PhoenixAdult.bundle#85]
I am trying to find this scene "Jessica And Cherie Robot Blowjob" https://www.spizoo.com/updates/Jessica-And-Cherie-Robot-Blowjob.html but I can't seem to find it.

**Include**
1. Scene URL - https://www.spizoo.com/updates/Jessica-And-Cherie-Robot-Blowjob.html
2. File Name - FirstClassPOV - Jessica And Cherie Robot Blowjob
3. Log File - [com.plexapp.agents.phoenixadult.log](https://github.com/DirtyRacer1337/PhoenixAdult.bundle/files/5914152/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Same as [#1177](https://github.com/PAhelper/PhoenixAdult.bundle/issues/1177)
