### ISSUE TITLE
PornDoe without actors

### ISSUE THREAD

**Issue by drraymond27** [DirtyRacer1337/PhoenixAdult.bundle#91]
PornDow no shows Actors cast

**Include**
1. https://letsdoeit.com/watch/5356/sensuous-pet.en.html
2. The White Boxxx - Sensuous Pet
3. [com.plexapp.agents.phoenixadult.log](https://github.com/DirtyRacer1337/PhoenixAdult.bundle/files/6184855/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Fixed in ad31c17494239fe0ec85a047f357990a18a6071f
