### ISSUE TITLE
Evolved Fights no match

### ISSUE THREAD

**Issue by drraymond27** [DirtyRacer1337/PhoenixAdult.bundle#95]
Evolved Fights No match with some videos

**Include**
1. https://www.evolvedfights.com/updates/Amilia-Onyx-vs-Will-Tile.html
2. Evolved Fights - Amilia Onyx vs Will Tile
3. 
[com.plexapp.agents.phoenixadult.log](https://github.com/DirtyRacer1337/PhoenixAdult.bundle/files/6369550/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Try with ab7637bfe1f10d76d58de5117769e2e3b0cbd98c

**Comment by drraymond27** [comment]
Perfect!, thanks
