### ISSUE TITLE
Adult Empire Still not shows the info

### ISSUE THREAD

**Issue by drraymond27** [DirtyRacer1337/PhoenixAdult.bundle#96]
Adult Empire still not working the info

https://www.adultdvdempire.com/553141/best-of-gregory-dark-the-porn-movies.html
Evil Angel - Gregory Dark's Flesh
[com.plexapp.agents.phoenixadult.log](https://github.com/DirtyRacer1337/PhoenixAdult.bundle/files/6371002/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
This is to @extant-squash
